### PR TITLE
nan: use npm version instead of harcoded url

### LINKED ISSUE #9: hard-coded dependency
Hello,

I'm trying to install electron-rebuild which has nslog as dependency and I get:
     ```fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz```
 
My proxies setting are OK (it works with others repo).

How about to replace:
```javascript
    "dependencies": {
        "nan": "https://atom.io/download/atom-shell/nan-1.6.1.tgz"
      }
```
by
```javascript
    "dependencies": {
        "nan": "1.6.1"
      }
```
?

Settings:
win32 x64
node v0.12.7
npm  v2.11.3

### PR DESCRIPTION
**Pull request by oligot**
Fixes #9

### CODE REVIEW

**Comment by thomasjo** [comment]
From memory, the current version of NAN is patched, and if that's the case, this change would break Atom. /cc @zcbenz

**Comment by ssreekanth** [comment]
pull request #11 takes care of #9 . This pull-request can be cancelled.

**Comment by paulcbetts** [comment]
@oligot Thanks for the PR regardless!

**Comment by oligot** [comment]
@paulcbetts And thanks for merging an improved version.

**Pull request closed without merging**
